profiles:
  - name: "SRE-Platform"
    resume_path: "curriculos/RESUME_LUIS_FELIX.md"
    positive_keywords:
      - "Go"
      - "Golang"
      - "Platform"
      - "SRE"
      - "Infrastructure"
      - "DevOps"
      - "Backend"
      - "Remote"
      - "Kubernetes"
    negative_keywords:
      - "Java"
      - "Frontend"
      - "Manager"
      - "Estágio"
      - "Júnior"
    trello_list_id: "698daef21893d14923a0c738"
    sources:
      jobicy_url: "https://jobicy.com/api/v2/remote-jobs?count=20&geo=europe&industry=admin"
      wwr_url: "https://remotive.com/remote-jobs/feed/devops"
      linkedin_url: ""
      jsearch_query: "SRE remote Europe"
      findwork_search: "golang devops"
      findwork_location: "remote"

  - name: "DotNet-Backend"
    resume_path: "curriculos/Luis_Felipe_Felix_Filho_Resume.md"
    positive_keywords:
      - ".NET"
      - "C#"
      - "Backend"
      - "ASP.NET"
      - "Azure"
      - "React"
      - "SQL Server"
      - "Remote"
    negative_keywords:
      - "Java"
      - "Frontend only"
      - "Manager"
      - "Estágio"
      - "Júnior"
    trello_list_id: "698daf132538fbe154aab112"
    sources:
      jobicy_url: "https://jobicy.com/api/v2/remote-jobs?count=20&geo=europe&industry=dev"
      wwr_url: ""
      linkedin_url: ""
      jsearch_query: ".NET developer remote Europe"
      findwork_search: "dotnet backend"
      findwork_location: "remote"
